# Generated by Django 2.1.1 on 2018-09-24 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='asignacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='clinica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.TextField()),
                ('numero_plazas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='consulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('presion_arterial', models.CharField(max_length=8)),
                ('id_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='diagnostico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='enfermedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sistema', models.TextField()),
                ('sintomas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('cupos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_barra', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('composicion', models.TextField()),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jvpm', models.CharField(max_length=10)),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dui', models.CharField(max_length=10)),
                ('ssn', models.CharField(max_length=25)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('f_nac', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='receta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posologia', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('id_enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.enfermedad')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.paciente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.producto')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=1)),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.horario')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.medico')),
            ],
        ),
        migrations.CreateModel(
            name='tipoConsulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tipoEnfermedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('telefono', models.TextField()),
                ('dui', models.TextField()),
                ('id_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.acceso')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.tipoProducto'),
        ),
        migrations.AddField(
            model_name='medico',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.usuario'),
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='id_tipoEnfermedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.tipoEnfermedad'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='id_enfermedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.enfermedad'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.schedule'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.usuario'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.tipoConsulta'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.schedule'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.paciente'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.usuario'),
        ),
    ]
